---
# handlers file for base (main.yml)

- name: stop and disable cloudmonitor
  systemd:
    daemon_reload: yes
    name: cloudmonitor
    state: stopped
    enabled: no
  when: cloud_provider == 'aliyun'

- name: start and enable lvm2-metad
  systemd:
    daemon_reload: yes
    name: lvm2-lvmetad
    state: started
    enabled: yes